In [1]:
import pandas as pd 
import numpy as np

In [24]:
pip install unidecode

Requirement already satisfied: unidecode in c:\ironhack\anaconda\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
from unidecode import unidecode

In [2]:
data = pd.read_csv('../Data/animales-peligro-extincion.csv')

In [3]:
data

,animal_id,nombre_cientifico,grupo/animal,familia,tipo,Nombre común,categoria/extincion
0,12397,Limoniscus violaceus,INVERTEBRADOS,INSECTA,Coleoptera,Escarabajo resorte,Vulnerable
1,11397,Pimelia granulicollis,INVERTEBRADOS,INSECTA,Coleoptera,Pimelia de las arenas,En peligro de extinción
2,68797,Rhopalomesites euphorbiae,INVERTEBRADOS,INSECTA,Coleoptera,Picudo de la tabaiba de monte,En peligro de extinción
3,32345,Euchloe bazae,INVERTEBRADOS,INSECTA,Lepidoptera,"Azufrada ibérca, Blanquiverdosa azufrada",En peligro de extinción
4,11818,Maculinea nausithous,INVERTEBRADOS,INSECTA,Lepidoptera,Hormiguera oscura,Vulnerable
...,...,...,...,...,...,...,...
498,20093,Hyperoodon ampullatus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio calderón septentrional,LESRPE
499,20095,Mesoplodon densirostris,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de Blainville,LESRPE
500,20096,Mesoplodon europaeus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de Gervais,LESRPE
501,20098,Mesoplodon mirus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de True,LESRPE
502,20099,Ziphius cavirostris,MAMÍFEROS,CETACEA,Hyperoodontidae,"Zifio de Cuvier, Zifio común",Vulnerable

In [4]:
data.reset_index(drop=True, inplace=True)

In [5]:
data

,animal_id,nombre_cientifico,grupo/animal,familia,tipo,Nombre común,categoria/extincion
0,12397,Limoniscus violaceus,INVERTEBRADOS,INSECTA,Coleoptera,Escarabajo resorte,Vulnerable
1,11397,Pimelia granulicollis,INVERTEBRADOS,INSECTA,Coleoptera,Pimelia de las arenas,En peligro de extinción
2,68797,Rhopalomesites euphorbiae,INVERTEBRADOS,INSECTA,Coleoptera,Picudo de la tabaiba de monte,En peligro de extinción
3,32345,Euchloe bazae,INVERTEBRADOS,INSECTA,Lepidoptera,"Azufrada ibérca, Blanquiverdosa azufrada",En peligro de extinción
4,11818,Maculinea nausithous,INVERTEBRADOS,INSECTA,Lepidoptera,Hormiguera oscura,Vulnerable
...,...,...,...,...,...,...,...
498,20093,Hyperoodon ampullatus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio calderón septentrional,LESRPE
499,20095,Mesoplodon densirostris,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de Blainville,LESRPE
500,20096,Mesoplodon europaeus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de Gervais,LESRPE
501,20098,Mesoplodon mirus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de True,LESRPE
502,20099,Ziphius cavirostris,MAMÍFEROS,CETACEA,Hyperoodontidae,"Zifio de Cuvier, Zifio común",Vulnerable

In [6]:
data['grupo/animal'].unique()

array(['INVERTEBRADOS', 'ANFIBIOS', 'REPTILES', 'AVES', 'MAMÍFEROS'],
      dtype=object)

In [7]:
data_1 = data.loc[data['grupo/animal'] == 'MAMÍFEROS']

In [8]:
data_1.reset_index(drop=True, inplace=True)

In [9]:
data_1

,animal_id,nombre_cientifico,grupo/animal,familia,tipo,Nombre común,categoria/extincion
0,10669,Atelerix algirus,MAMÍFEROS,ERINACEOMORPHA,Erinaceidae,Erizo moruno,LESRPE
1,10948,Crocidura canariensis,MAMÍFEROS,SORICOMORPHA,Soricidae,Musaraña canaria,Vulnerable
2,12059,Galemys pyrenaicus,MAMÍFEROS,SORICOMORPHA,Talpidae,Desmán ibérico,En peligro de extinción
3,11230,Rhinolophus euryale,MAMÍFEROS,CHIROPTERA,Rhinolophidae,Murciélago mediterrráneo de herradura,Vulnerable
4,11264,Rhinolophus ferrumequinum,MAMÍFEROS,CHIROPTERA,Rhinolophidae,Murciélago grande de herradura,Vulnerable
...,...,...,...,...,...,...,...
68,20093,Hyperoodon ampullatus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio calderón septentrional,LESRPE
69,20095,Mesoplodon densirostris,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de Blainville,LESRPE
70,20096,Mesoplodon europaeus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de Gervais,LESRPE
71,20098,Mesoplodon mirus,MAMÍFEROS,CETACEA,Hyperoodontidae,Zifio de True,LESRPE
72,20099,Ziphius cavirostris,MAMÍFEROS,CETACEA,Hyperoodontidae,"Zifio de Cuvier, Zifio común",Vulnerable

In [10]:
data_1['nombre_cientifico'].unique()

array(['Atelerix algirus ', 'Crocidura canariensis', 'Galemys pyrenaicus',
       'Rhinolophus euryale ', 'Rhinolophus ferrumequinum ',
       'Rhinolophus hipposideros', 'Rhinolophus mehelyi ',
       'Barbastella barbastellus',
       'Eptesicus isabellinus(antes E. serotinus)', 'Eptesicus serotinus',
       'Hypsugo savii', 'Myotis alcathoe (= M. mystacinus)',
       'Myotis bechsteinii ', 'Myotis blythii ', 'Myotis capaccinii',
       'Myotis daubentonii', 'Myotis emarginatus  ', 'Myotis myotis ',
       'Myotis mystacinus ', 'Myotis nattereri (=M. escalerai)',
       'Myotis punicus', 'Nyctalus lasiopterus ', 'Nyctalus leisleri',
       'Nyctalus noctula  ', 'Pipistrellus kuhlii',
       'Pipistrellus maderensis', 'Pipistrellus nathusii',
       'Pipistrellus pipistrellus',
       'Pipistrellus pygmaeus (antes P. pipistrellus)',
       'Plecotus auritus', 'Plecotus austriacus',
       'Plecotus macrobullaris', 'Plecotus teneriffae',
       'Miniopterus schreibersii  ', 'Tadarida teniotis', 'Castor fiber',
       'Eliomys munbyanus', 'Iberomys (Microtus) cabrerae', 'Canis lupus',
       'Ursus arctos', 'Lutra lutra', 'Mustela erminea',
       'Mustela lutreola', 'Felis silvestris', 'Lynx pardinus',
       'Monachus monachus', 'Balaenoptera acutorostrata',
       'Balaenoptera borealis', 'Balaenoptera edeni/brydei',
       'Balaenoptera musculus', 'Balaenoptera physalus  ',
       'Megaptera novaeangliae', 'Kogia breviceps', 'Kogia sima',
       'Eubalaena glacialis', 'Physeter macrocephalus',
       'Delphinus delphis', 'Globicephala macrorhynchus',
       'Globicephala melas', 'Grampus griseus', 'Lagenodelphis hosei',
       'Orcinus orca', 'Pseudorca crassidens', 'Stenella coeruleoalba',
       'Stenella frontalis', 'Steno bredanensis', 'Tursiops truncatus ',
       'Phocoena phocoena  ', 'Hyperoodon ampullatus',
       'Mesoplodon densirostris', 'Mesoplodon europaeus',
       'Mesoplodon mirus', 'Ziphius cavirostris'], dtype=object)

In [26]:
data_1 = data_1.applymap(lambda x: unidecode(x) if isinstance(x, str) else x)

In [28]:
data_5 = data_5.applymap(lambda x: unidecode(x) if isinstance(x, str) else x)

In [27]:
#data_1.to_csv('MAMÍFEROS-peligro-extincion.csv', index=False)

In [12]:
data_2 = data.loc[data['grupo/animal'] == 'INVERTEBRADOS']

In [13]:
data_2.reset_index(drop=True, inplace=True)

In [14]:
#data_2.to_csv('INVERTEBRADOS-peligro-extincion.csv', index=False)

In [15]:
data_3 = data.loc[data['grupo/animal'] == 'ANFIBIOS']

In [16]:
data_2.reset_index(drop=True, inplace=True)

In [17]:
#data_3.to_csv('ANFIBIOS-peligro-extincion.csv', index=False)

In [18]:
data_4 = data.loc[data['grupo/animal'] == 'REPTILES']

In [19]:
data_4.reset_index(drop=True, inplace=True)

In [20]:
#data_4.to_csv('REPTILES-peligro-extincion.csv', index=False)

In [21]:
data_5 = data.loc[data['grupo/animal'] == 'AVES']

In [22]:
data_5.reset_index(drop=True, inplace=True)

In [29]:
#data_5.to_csv('AVES-peligro-extincion.csv', index=False)